-- Trade Site Factory: production Supabase/PostgreSQL schema.
-- Tenant isolation is enforced through business_id and RLS policies in deployment.
create table businesses (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, trading_name text, trade_type text not null default 'scaffolding', primary_contact text, public_phone text, whatsapp_phone text, email text, base_town text, postcode text, years_trading integer, family_run boolean, residential_work boolean default true, commercial_work boolean default false, site_status text not null default 'draft' check (site_status in ('draft','preview','published')), created_at timestamptz not null default now());
create table services (id uuid primary key default gen_random_uuid(), trade_type text not null, name text not null, slug text not null, unique(trade_type,slug));
create table business_services (business_id uuid references businesses(id) on delete cascade, service_id uuid references services(id) on delete cascade, primary key(business_id,service_id));
create table service_areas (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, name text not null, slug text not null, unique(business_id,slug));
create table projects (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, service_id uuid references services(id), title text not null, slug text not null, location text not null, description text, completed_on date, published boolean not null default false, unique(business_id,slug));
create table project_images (id uuid primary key default gen_random_uuid(), project_id uuid not null references projects(id) on delete cascade, storage_path text not null, alt_text text not null, is_featured boolean not null default false, sort_order integer not null default 0);
create table testimonials (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, quote text not null, customer_name text, location text, project_type text, published boolean not null default false);
create table accreditations (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, name text not null, reference text, storage_path text);
create table site_configurations (business_id uuid primary key references businesses(id) on delete cascade, template_key text not null default 'scaffolding-v1', published_at timestamptz, custom_domain text unique);
create table enquiries (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, reference text not null, customer_name text not null, mobile text not null, email text, location text not null, preferred_contact text not null, work_type text not null, required_when text, description text not null, storeys text not null, access_areas text not null, width text not null, dimensions text, status text not null default 'new' check (status in ('new','contacted','quoted','won','lost')), created_at timestamptz not null default now(), unique(business_id,reference));
create table enquiry_images (id uuid primary key default gen_random_uuid(), enquiry_id uuid not null references enquiries(id) on delete cascade, storage_path text not null, sort_order integer not null default 0);
create table generated_content (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, content_key text not null, value text not null, source_facts jsonb not null default '{}', generator text not null default 'deterministic', created_at timestamptz not null default now());
create table audit_events (id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id) on delete cascade, actor_id uuid, action text not null, entity_type text not null, entity_id uuid, payload jsonb not null default '{}', created_at timestamptz not null default now());
