import test from 'node:test';
import assert from 'node:assert/strict';
import { businessCopy, canTransition, declaredArea, imageSizeValid, imageTypeValid, nextReference, normalisePhone, projectBySlug, publicProjects, selectedService, slugify, validEnquiry, whatsAppUrl, type Project } from '../lib/domain/index.ts';
import { business, projects } from '../lib/data/demo.ts';

test('1 slug generation',()=>assert.equal(slugify(' Temporary Roof Scaffolding! '),'temporary-roof-scaffolding'));
test('2 UK phone normalisation',()=>assert.equal(normalisePhone('07700 900123'),'447700900123'));
test('3 WhatsApp URL includes encoded message',()=>assert.equal(whatsAppUrl('07700 900123','Quote Q-1001'),'https://wa.me/447700900123?text=Quote%20Q-1001'));
test('4 empty copy generation remains grammatical',()=>assert.equal(businessCopy(undefined,[],[]),'We provide scaffolding services.'));
test('5 one-service copy',()=>assert.equal(businessCopy(undefined,['Domestic scaffolding'],[]),'We provide Domestic scaffolding.'));
test('6 multiple-service and area copy',()=>assert.equal(businessCopy(17,['Domestic scaffolding','Temporary roof'],['Chester','Wrexham']),`With more than 17 years’ experience, we provide Domestic scaffolding and Temporary roof throughout Chester and Wrexham.`));
test('7 project filtering isolates tenants',()=>assert.equal(publicProjects(projects,'another-business').length,0));
test('8 published projects exclude drafts',()=>{const draft:Project={...projects[0],id:'draft',published:false};assert.equal(publicProjects([...projects,draft],business.id).length,3)});
test('9 known project resolution',()=>assert.equal(projectBySlug(projects,business.id,'temporary-roof-scaffolding-hoole-chester')?.id,'p1'));
test('10 unknown project resolution',()=>assert.equal(projectBySlug(projects,business.id,'unknown'),undefined));
test('11 selected service resolution',()=>assert.equal(selectedService(business.services,'temporary-roof'),'Temporary roof'));
test('12 unknown service rejection',()=>assert.equal(selectedService(business.services,'plumbing'),undefined));
test('13 declared area resolution',()=>assert.equal(declaredArea(business.areas,'north-wales'),'North Wales'));
test('14 unknown area rejection',()=>assert.equal(declaredArea(business.areas,'london'),undefined));
test('15 enquiry required-field validation',()=>{assert.ok(validEnquiry({name:'A',mobile:'07',location:'Chester',work:'Roofing',storeys:'2 storeys',access:'Front',width:'5–10m',description:'Repair'}));assert.equal(validEnquiry({name:'A'}),false)});
test('16 enquiry reference allocation never reuses lower gaps',()=>assert.equal(nextReference([{reference:'Q-1001'},{reference:'Q-1008'},{reference:'invalid'}]),'Q-1009'));
test('17 image type validation',()=>{assert.ok(imageTypeValid({type:'image/jpeg'}));assert.equal(imageTypeValid({type:'application/pdf'}),false)});
test('18 image size validation',()=>{assert.ok(imageSizeValid({size:10_000_000}));assert.equal(imageSizeValid({size:10_000_001}),false)});
test('19 allowed status transition',()=>assert.ok(canTransition('new','contacted')));
test('20 rejected status transition',()=>assert.equal(canTransition('won','quoted'),false));
