/* eslint-disable @next/next/no-img-element, react-hooks/set-state-in-effect */
'use client';
import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
import { usePathname } from 'next/navigation';
import { PhotoPicker } from './photo-picker';
import { demoRepository, type Business } from '../lib/data/repository';
import { businessCopy, canTransition, declaredArea, type Enquiry, nextReference, projectBySlug, type Project, publicProjects, selectedService, slugify, validEnquiry, whatsAppUrl } from '../lib/domain';

type ButtonProps=React.ButtonHTMLAttributes<HTMLButtonElement>&{children:React.ReactNode};
const Button=({children,...props}:ButtonProps)=><button className="btn" {...props}>{children}</button>;
const Back=({onClick}:{onClick:()=>void})=><button className="back" type="button" onClick={onClick}>← Back</button>;
const NotFound=()=> <main className="form-page"><p className="eyebrow">404</p><h1>Page not found</h1><p>That page is not part of this website.</p></main>;
const initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(0,2).map(word=>word[0]).join('').toUpperCase();

export function CompletionApp(){
 const pathname=usePathname()||'/';
 const[business,setBusiness]=useState<Business|null>(null);
 const[projects,setProjects]=useState<Project[]>([]);
 const[enquiries,setEnquiries]=useState<Enquiry[]>([]);
 useEffect(()=>{setBusiness(demoRepository.loadBusiness());setProjects(demoRepository.loadProjects());setEnquiries(demoRepository.loadEnquiries())},[]);
 if(!business)return null;
 const saveBusiness=(next:Business)=>{demoRepository.saveBusiness(next);setBusiness(next)};
 const saveProjects=(next:Project[])=>{demoRepository.saveProjects(next);setProjects(next)};
 const saveEnquiries=(next:Enquiry[])=>{demoRepository.saveEnquiries(next);setEnquiries(next)};
 return pathname.startsWith('/owner')?<Owner business={business} saveBusiness={saveBusiness} projects={projects} saveProjects={saveProjects} enquiries={enquiries} saveEnquiries={saveEnquiries}/>:<PublicSite pathname={pathname} business={business} projects={projects} enquiries={enquiries} saveEnquiries={saveEnquiries}/>;
}

type OwnerProps={business:Business;saveBusiness:(business:Business)=>void;projects:Project[];saveProjects:(projects:Project[])=>void;enquiries:Enquiry[];saveEnquiries:(enquiries:Enquiry[])=>void};
function Owner({business,saveBusiness,projects,saveProjects,enquiries,saveEnquiries}:OwnerProps){
 const[view,setView]=useState<'home'|'add'|'jobs'|'edit'|'details'|'enquiries'|'live'>('home');
 const[selected,setSelected]=useState<Project|null>(null);
 const[draft,setDraft]=useState<Partial<Project>>({service:business.services[0]||'Other',images:[]});
 const[error,setError]=useState('');
 const startAdd=()=>{setDraft({service:business.services[0]||'Other',images:[]});setError('');setView('add')};
 const publish=()=>{if(!draft.location?.trim()){setError('Add the town or location before publishing.');return}const title=draft.title?.trim()||`${draft.service} in ${draft.location.trim()}`;const project:Project={id:crypto.randomUUID(),businessId:business.id,slug:slugify(`${title}-${Date.now()}`),title,service:draft.service||'Other',location:draft.location.trim(),description:draft.description?.trim()||`Completed ${draft.service?.toLowerCase()} in ${draft.location.trim()}.`,published:true,images:draft.images||[]};saveProjects([project,...projects]);setSelected(project);setView('live')};
 const updateProject=(project:Project)=>saveProjects(projects.map(item=>item.id===project.id?project:item));
 if(view==='add')return <OwnerPage><Back onClick={()=>setView('home')}/><h1>Add today’s job</h1><p>Just the facts. Your website handles the rest.</p><section className="owner-card"><label>1. What did you do today?<select value={draft.service} onChange={event=>setDraft({...draft,service:event.target.value})}>{[...new Set([...business.services,'Other'])].map(service=><option key={service}>{service}</option>)}</select></label><label>2. Where was the job?<input value={draft.location||''} placeholder="e.g. Wrexham" onChange={event=>setDraft({...draft,location:event.target.value})}/></label><div><h2>3. Add photos</h2><PhotoPicker images={(draft.images||[]).map(url=>({url}))} onChange={images=>setDraft({...draft,images:images.map(image=>image.url)})}/></div><label>4. What did you do? <small>(optional)</small><textarea rows={4} value={draft.description||''} placeholder="e.g. Two-storey access scaffold completed in Wrexham." onChange={event=>setDraft({...draft,description:event.target.value})}/></label>{error&&<p className="error" role="alert">{error}</p>}<Button type="button" onClick={publish}>PUBLISH JOB</Button></section></OwnerPage>;
 if(view==='live'&&selected)return <OwnerPage extra="success-page"><h1>Your job is live</h1><p>It now appears automatically on your website.</p><Link className="btn" href={`/sites/${business.slug}/projects/${selected.slug}`}>VIEW IT</Link><button className="btn outline" onClick={startAdd}>ADD ANOTHER JOB</button><button className="back" onClick={()=>setView('home')}>Back to your website controls</button></OwnerPage>;
 if(view==='jobs')return <OwnerPage><Back onClick={()=>setView('home')}/><h1>My jobs</h1><div className="job-list">{projects.map(project=><button className="job-row" key={project.id} onClick={()=>{setSelected(project);setView('edit')}}>{project.images[0]?<img src={project.images[0]} alt=""/>:<span className="job-placeholder"/>}<span><b>{project.published?'LIVE':'DRAFT'} · {project.title}</b><small>{project.location} · {project.service}</small></span><i>→</i></button>)}</div></OwnerPage>;
 if(view==='edit'&&selected)return <OwnerPage><Back onClick={()=>setView('jobs')}/><h1>Edit job</h1><label>Service<select value={selected.service} onChange={event=>setSelected({...selected,service:event.target.value})}>{[...new Set([...business.services,'Other'])].map(service=><option key={service}>{service}</option>)}</select></label><label>Location<input value={selected.location} onChange={event=>setSelected({...selected,location:event.target.value})}/></label><label>Details<textarea rows={4} value={selected.description} onChange={event=>setSelected({...selected,description:event.target.value})}/></label><h2>Photos</h2><PhotoPicker images={selected.images.map(url=>({url}))} onChange={images=>setSelected({...selected,images:images.map(image=>image.url)})} label="ADD MORE PHOTOS"/><div className="owner-actions"><Button onClick={()=>{updateProject(selected);setView('jobs')}}>SAVE CHANGES</Button><button className="btn outline" onClick={()=>{updateProject({...selected,published:!selected.published});setView('jobs')}}>{selected.published?'UNPUBLISH':'PUBLISH'}</button><button className="danger-button" onClick={()=>{if(window.confirm('Delete this job?')){saveProjects(projects.filter(project=>project.id!==selected.id));setView('jobs')}}}>DELETE JOB</button></div></OwnerPage>;
 if(view==='details')return <BusinessDetails business={business} saveBusiness={saveBusiness} onBack={()=>setView('home')}/>;
 if(view==='enquiries')return <OwnerEnquiries business={business} enquiries={enquiries} saveEnquiries={saveEnquiries} onBack={()=>setView('home')}/>;
 return <OwnerPage><h1>Your website</h1><button className="big-action" onClick={startAdd}>+ ADD TODAY’S JOB</button><div className="owner-menu"><button onClick={()=>setView('enquiries')}>NEW ENQUIRIES <b>{enquiries.filter(item=>item.status==='new').length}</b></button><button onClick={()=>setView('jobs')}>MY JOBS <b>{projects.length}</b></button><button onClick={()=>setView('details')}>BUSINESS DETAILS</button><Link href={`/sites/${business.slug}`}>VIEW WEBSITE ↗</Link></div></OwnerPage>;
}

function OwnerPage({children,extra=''}:{children:React.ReactNode;extra?:string}){return <main className={`owner ${extra}`}><p className="demo">DEMO MODE · YOUR WEBSITE</p>{children}</main>}
function BusinessDetails({business,saveBusiness,onBack}:{business:Business;saveBusiness:(business:Business)=>void;onBack:()=>void}){const update=(key:'name'|'phone'|'whatsapp'|'email'|'town',value:string)=>saveBusiness({...business,[key]:value});return <OwnerPage><Back onClick={onBack}/><h1>Business details</h1><label>Business name<input value={business.name} onChange={event=>update('name',event.target.value)}/></label><label>Public phone<input value={business.phone} onChange={event=>update('phone',event.target.value)}/></label><label>WhatsApp number<input value={business.whatsapp} onChange={event=>update('whatsapp',event.target.value)}/></label><label>Email<input value={business.email||''} onChange={event=>update('email',event.target.value)}/></label><label>Base town<input value={business.town} onChange={event=>update('town',event.target.value)}/></label><label>Years trading<input type="number" min="0" value={business.years} onChange={event=>saveBusiness({...business,years:Number(event.target.value)})}/></label><h2>Services offered</h2><ToggleList values={['Domestic scaffolding','Commercial scaffolding','Temporary roof','Roofing access']} selected={business.services} onChange={services=>saveBusiness({...business,services})}/><h2>Areas covered</h2><ToggleList values={['Chester','Wrexham','Mold','North Wales']} selected={business.areas} onChange={areas=>saveBusiness({...business,areas})}/></OwnerPage>}
function ToggleList({values,selected,onChange}:{values:string[];selected:string[];onChange:(items:string[])=>void}){return <div className="choices">{values.map(value=><button type="button" className={selected.includes(value)?'on':''} key={value} onClick={()=>onChange(selected.includes(value)?selected.filter(item=>item!==value):[...selected,value])}>{value}</button>)}</div>}
function OwnerEnquiries({business,enquiries,saveEnquiries,onBack}:{business:Business;enquiries:Enquiry[];saveEnquiries:(items:Enquiry[])=>void;onBack:()=>void}){return <OwnerPage><Back onClick={onBack}/><h1>New enquiries</h1><div className="enquiry-list">{enquiries.map(enquiry=><article className="lead" key={enquiry.id}><span className="status-pill">{enquiry.status}</span><h2>{enquiry.reference} · {enquiry.name}</h2><p>{enquiry.location} · {enquiry.work}<br/>{enquiry.storeys} · {enquiry.width} · {enquiry.access}</p><p>{enquiry.description}</p>{enquiry.photos.length>0&&<div className="enquiry-photos">{enquiry.photos.map((photo,index)=><a href={photo} target="_blank" rel="noreferrer" key={`${enquiry.id}-${index}`}><img src={photo} alt={`Customer photo ${index+1} for ${enquiry.reference}`}/></a>)}</div>}<div className="owner-actions"><a className="btn" href={`tel:${enquiry.mobile}`}>CALL</a><a className="btn outline" target="_blank" rel="noreferrer" href={whatsAppUrl(enquiry.mobile,`Hi ${enquiry.name}, it’s ${business.name}. We’ve received your website quote request ${enquiry.reference}.`)}>WHATSAPP</a></div><div className="choices status-actions">{(['new','contacted','quoted','won','lost'] as Enquiry['status'][]).filter(status=>status!==enquiry.status&&canTransition(enquiry.status,status)).map(status=><button key={status} onClick={()=>saveEnquiries(enquiries.map(item=>item.id===enquiry.id?{...item,status}:item))}>MARK {status.toUpperCase()}</button>)}</div></article>)}</div></OwnerPage>}

type PublicProps={pathname:string;business:Business;projects:Project[];enquiries:Enquiry[];saveEnquiries:(items:Enquiry[])=>void};
function PublicSite({pathname,business,projects,enquiries,saveEnquiries}:PublicProps){
 const root=`/sites/${business.slug}`;
 if(!pathname.startsWith(root)||pathname.startsWith('/sites/')&&!pathname.startsWith(`${root}/`)&&pathname!==root)return <NotFound/>;
 const relative=pathname.slice(root.length)||'/';
 const chrome=(content:React.ReactNode)=><><PublicHeader business={business}/>{content}<MobileActions business={business}/></>;
 if(relative==='/quote')return chrome(<QuoteForm business={business} enquiries={enquiries} saveEnquiries={saveEnquiries}/>);
 if(relative==='/projects')return chrome(<Listing eyebrow="Recent work" title="Jobs completed locally."><ProjectCards business={business} projects={publicProjects(projects,business.id)}/></Listing>);
 if(relative.startsWith('/projects/')){const project=projectBySlug(projects,business.id,relative.slice('/projects/'.length));return project?chrome(<ProjectDetail business={business} project={project}/>):<NotFound/>}
 if(relative==='/services')return chrome(<Listing eyebrow="What we do" title="Scaffolding services."><div className="cards">{business.services.map(service=><Link className="card" href={`${root}/services/${slugify(service)}`} key={service}><h2>{service}</h2><p>Find out how we can help with this type of work.</p><b>→</b></Link>)}</div></Listing>);
 if(relative.startsWith('/services/')){const service=selectedService(business.services,relative.slice('/services/'.length));return service?chrome(<ServicePage business={business} service={service} projects={projects}/>):<NotFound/>}
 if(relative==='/areas')return chrome(<Listing eyebrow="Where we work" title="Areas we cover."><div className="cards">{business.areas.map(area=><Link className="card" href={`${root}/areas/${slugify(area)}`} key={area}><h2>{area}</h2><b>→</b></Link>)}</div></Listing>);
 if(relative.startsWith('/areas/')){const area=declaredArea(business.areas,relative.slice('/areas/'.length));return area?chrome(<AreaPage business={business} area={area} projects={projects}/>):<NotFound/>}
 if(relative==='/about')return chrome(<Listing eyebrow="About us" title={business.name}><p className="large-copy">{businessCopy(business.years,business.services,business.areas)}</p><p>Based in {business.town}. Call {business.phone} to discuss your project.</p></Listing>);
 if(relative!=='/')return <NotFound/>;
 return chrome(<Home business={business} projects={projects}/>);
}

function PublicHeader({business}:{business:Business}){const root=`/sites/${business.slug}`;return <header className="header"><Link className="logo" href={root}><b>{initials(business.name)}</b><span>{business.name}<small>TRADE WEBSITE</small></span></Link><nav><Link href={root}>Home</Link><Link href={`${root}/services`}>Services</Link><Link href={`${root}/projects`}>Recent Jobs</Link><Link href={`${root}/areas`}>Areas</Link><Link href={`${root}/about`}>About</Link></nav><Link className="btn" href={`${root}/quote`}>Get a quote</Link></header>}
function MobileActions({business}:{business:Business}){return <div className="sticky"><a href={`tel:${business.phone.replace(/\s/g,'')}`}>CALL</a><a target="_blank" rel="noreferrer" href={whatsAppUrl(business.whatsapp,'Hi, I would like a quote.')}>WHATSAPP</a><Link href={`/sites/${business.slug}/quote`}>GET A QUOTE</Link></div>}
function Listing({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <main className="section listing-page"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{children}</main>}
function Home({business,projects}:{business:Business;projects:Project[]}){return <main><section className="hero"><div><p className="eyebrow">Scaffolding across {business.areas.slice(0,2).join(' & ')||business.town}</p><h1>Safe access.<br/><em>Properly planned.</em></h1><p>{businessCopy(business.years,business.services,business.areas)}</p><div className="actions"><Link className="btn" href={`/sites/${business.slug}/quote`}>GET A QUOTE</Link><a href={`tel:${business.phone.replace(/\s/g,'')}`}>Call {business.phone}</a></div></div><DemoVisual/></section><section className="section"><p className="eyebrow">Recent jobs</p><ProjectCards business={business} projects={publicProjects(projects,business.id).slice(0,3)}/></section></main>}
function ProjectCards({business,projects}:{business:Business;projects:Project[]}){return <div className="project-grid">{projects.map(project=><Link className="project" href={`/sites/${business.slug}/projects/${project.slug}`} key={project.id}>{project.images[0]?<img className="project-cover" src={project.images[0]} alt={`${project.title} in ${project.location}`}/>:<DemoVisual/>}<small>{project.location}</small><h2>{project.title}</h2></Link>)}</div>}
function ProjectDetail({business,project}:{business:Business;project:Project}){return <main className="project-page"><div><p className="eyebrow">Recent work · {project.location}</p><h1>{project.title}</h1><p>{project.description}</p><a className="text-link" target="_blank" rel="noreferrer" href={whatsAppUrl(business.whatsapp,`Hi, I’ve just seen your ${project.title} project in ${project.location}. I’m looking for something similar.`)}>Ask about a similar job →</a></div><div className="project-gallery">{project.images.length?project.images.map((image,index)=><img src={image} alt={`${project.title} in ${project.location}, photo ${index+1}`} key={`${project.id}-${index}`}/>):<DemoVisual/>}</div></main>}
function ServicePage({business,service,projects}:{business:Business;service:string;projects:Project[]}){const related=publicProjects(projects,business.id).filter(project=>project.service===service);return <Listing eyebrow={`Service in ${business.town}`} title={service}><p className="large-copy">We provide {service.toLowerCase()} throughout {business.areas.join(', ')}.</p>{related.length>0&&<><h2>Related work</h2><ProjectCards business={business} projects={related}/></>}</Listing>}
function AreaPage({business,area,projects}:{business:Business;area:string;projects:Project[]}){const related=publicProjects(projects,business.id).filter(project=>project.location.toLowerCase().includes(area.toLowerCase()));return <Listing eyebrow="Area covered" title={area}><p className="large-copy">{business.name} provides its selected scaffolding services in {area}.</p>{related.length>0&&<><h2>Recent work in {area}</h2><ProjectCards business={business} projects={related}/></>}</Listing>}
function DemoVisual(){return <div className="visual" role="img" aria-label="Demo scaffolding project placeholder"><i/><i/><i/><span>DEMO PROJECT</span></div>}

function QuoteForm({business,enquiries,saveEnquiries}:{business:Business;enquiries:Enquiry[];saveEnquiries:(items:Enquiry[])=>void}){
 const[form,setForm]=useState<Partial<Enquiry>>({preferredContact:'Phone',photos:[]});
 const[error,setError]=useState('');
 const[reference,setReference]=useState('');
 const update=(key:keyof Enquiry,value:string|string[])=>setForm(current=>({...current,[key]:value}));
 const submit=(event:FormEvent)=>{event.preventDefault();setError('');if(!validEnquiry(form)){setError('Complete the required details. “Not sure” is fine where offered.');return}const enquiry:Enquiry={...form as Enquiry,id:crypto.randomUUID(),businessId:business.id,reference:nextReference(enquiries),status:'new',photos:form.photos||[]};try{saveEnquiries([enquiry,...enquiries]);setReference(enquiry.reference)}catch{setError('We could not save your enquiry. Your details are still here—please try again.')}};
 if(reference)return <main className="form-page success-page"><p className="eyebrow">Enquiry sent</p><h1>Thanks — we’ve got it</h1><p>Your enquiry and {form.photos?.length||0} photo{form.photos?.length===1?'':'s'} have been sent to {business.name}.</p><b className="ref">{reference}</b><a className="btn" target="_blank" rel="noreferrer" href={whatsAppUrl(business.whatsapp,`Hi, I’ve just submitted quote request ${reference} through your website.`)}>CONTINUE ON WHATSAPP</a></main>;
 const choices=[['work','What is the work for?',['Roofing','Chimney','Rendering','Painting','Windows','Extension','Solar','New build','Other','Not sure']],['storeys','Storeys / property height',['Bungalow','2 storeys','3 storeys','4+','Not sure']],['access','Access required',['Front','Rear','Left','Right','Whole property','Not sure']],['width','Approximate width',['Under 5m','5–10m','10–20m','20m+','Not sure']]] as const;
 return <main className="form-page"><p className="eyebrow">Request a quote</p><h1>Tell us about the job.</h1><p>You don’t need to know scaffolding terminology.</p><form onSubmit={submit}><fieldset><legend>Your details</legend><label>Name*<input value={form.name||''} onChange={event=>update('name',event.target.value)}/></label><label>Mobile*<input type="tel" value={form.mobile||''} onChange={event=>update('mobile',event.target.value)}/></label><label>Email<input type="email" value={form.email||''} onChange={event=>update('email',event.target.value)}/></label><label>Postcode or location*<input value={form.location||''} onChange={event=>update('location',event.target.value)}/></label><label>Preferred contact method<select value={form.preferredContact} onChange={event=>update('preferredContact',event.target.value)}><option>Phone</option><option>WhatsApp</option><option>Email</option></select></label></fieldset><fieldset><legend>About the work</legend>{choices.map(([key,label,options])=><label key={key}>{label}*<select value={String(form[key]||'')} onChange={event=>update(key,event.target.value)}><option value="">Choose…</option>{options.map(option=><option key={option}>{option}</option>)}</select></label>)}<label>Optional dimensions<input value={form.dimensions||''} placeholder="e.g. 8m wide" onChange={event=>update('dimensions',event.target.value)}/></label><label>Description*<textarea rows={4} value={form.description||''} onChange={event=>update('description',event.target.value)}/></label></fieldset><fieldset><legend>Customer photos</legend><p>Photos help us understand the job. If possible include the front of the property, access route and area needing work.</p><PhotoPicker images={(form.photos||[]).map(url=>({url}))} onChange={photos=>update('photos',photos.map(photo=>photo.url))}/></fieldset>{error&&<p className="error" role="alert">{error}</p>}<Button type="submit">SEND QUOTE REQUEST</Button></form></main>
}
