export type Status = 'new' | 'contacted' | 'quoted' | 'won' | 'lost';
export type Project = { id:string; businessId:string; slug:string; title:string; service:string; location:string; description:string; published:boolean; images:string[] };
export type Enquiry = { id:string; businessId:string; reference:string; name:string; mobile:string; email?:string; location:string; preferredContact?:string; work:string; storeys:string; access:string; width:string; dimensions?:string; description:string; photos:string[]; status:Status };
export const slugify = (value:string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
export const normalisePhone = (value:string) => value.replace(/[^0-9]/g, '').replace(/^00/, '').replace(/^0/, '44');
export const whatsAppUrl = (phone:string, message:string) => `https://wa.me/${normalisePhone(phone)}?text=${encodeURIComponent(message)}`;
export const list = (items:string[]) => items.length < 2 ? items[0] || '' : items.length === 2 ? items.join(' and ') : `${items.slice(0, -1).join(', ')} and ${items.at(-1)}`;
export const businessCopy = (years?:number, services:string[]=[], areas:string[]=[]) => { const subject=services.length?list(services):'scaffolding services'; const where=areas.length?` throughout ${list(areas)}`:''; return years?`With more than ${years} years’ experience, we provide ${subject}${where}.`:`We provide ${subject}${where}.`; };
/** Short public header descriptor, e.g. "SCAFFOLDING · CHESTER & WREXHAM" — never platform/template wording (mission: "TRADE WEBSITE" must never appear publicly). Falls back to trade type alone with no location data, or to the location alone if trade type is somehow blank. */
export const businessDescriptor = (tradeType:string, areas:string[]=[], town='') => { const trade=(tradeType||'').trim().toUpperCase(); const location=areas.slice(0,2).join(' & ')||town.trim(); return trade ? (location?`${trade} · ${location}`:trade) : location; };
export const validEnquiry = (item:Partial<Enquiry>) => Boolean(item.name?.trim() && item.mobile?.trim() && item.location?.trim() && item.work && item.storeys && item.access && item.width && item.description?.trim());
export const nextReference = (items:Pick<Enquiry,'reference'>[]) => { const highest=items.reduce((max,item)=>{const match=/^Q-(\d+)$/.exec(item.reference);return match?Math.max(max,Number(match[1])):max},1000); return `Q-${highest+1}`; };
const transitions:Record<Status,Status[]>={new:['contacted','lost'],contacted:['quoted','lost'],quoted:['won','lost'],won:[],lost:[]};
export const canTransition = (from:Status,to:Status) => from===to || transitions[from].includes(to);
export const imageTypeValid = (file:Pick<File,'type'>) => file.type.startsWith('image/');
export const imageSizeValid = (file:Pick<File,'size'>) => file.size <= 10_000_000;
export const imageValid = (file:Pick<File,'type'|'size'>) => imageTypeValid(file) && imageSizeValid(file);
export const publicProjects = (projects:Project[],businessId:string) => projects.filter(project=>project.businessId===businessId&&project.published);
export const projectBySlug = (projects:Project[],businessId:string,slug:string) => publicProjects(projects,businessId).find(project=>project.slug===slug);
export const selectedService = (services:string[],slug:string) => services.find(service=>slugify(service)===slug);
export const declaredArea = (areas:string[],slug:string) => areas.find(area=>slugify(area)===slug);
